In [ ]:
import tensorflow as tf


In [ ]:
tensor_zero_d=tf.constant(4)
print(tensor_zero_d)


tf.Tensor(4, shape=(), dtype=int32)


In [ ]:
tensor_one_d=tf.constant([2,0,-3])
print(tensor_one_d)

tf.Tensor([ 2  0 -3], shape=(3,), dtype=int32)


In [ ]:
tensor_two_d=tf.constant([[1,2,3],
                         [4,5,6],
                         [7,8,9]])
print(tensor_two_d)

tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)


In [ ]:
tensor_three_d=tf.constant([[[5,3,8],[7,8,9]],[[8,9,10],[2,6,8]]])
print(tensor_three_d)

tf.Tensor(
[[[ 5  3  8]
  [ 7  8  9]]

 [[ 8  9 10]
  [ 2  6  8]]], shape=(2, 2, 3), dtype=int32)


In [ ]:
tensor_four_d=tf.constant(
    [
    [
        [[5,3,8],[7,8,9]],
         [[8,9,10],[2,6,8]]
        ],
    [
        [
            [1,2,8],
            [0,3,9]
            ],
         [[9,6,10],
          [2,1,8]]]])
print(tensor_four_d)
tensor_one=tf.ones([1,2,7])
print(tensor_one)

tf.Tensor(
[[[[ 5  3  8]
   [ 7  8  9]]

  [[ 8  9 10]
   [ 2  6  8]]]


 [[[ 1  2  8]
   [ 0  3  9]]

  [[ 9  6 10]
   [ 2  1  8]]]], shape=(2, 2, 2, 3), dtype=int32)
tf.Tensor(
[[[1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1.]]], shape=(1, 2, 7), dtype=float32)


Day2: TENSOR MATH

In [ ]:
from tensorflow import math
x=tf.constant([-2,3,5,-7])
print(tf.abs(x))

tf.Tensor([2 3 5 7], shape=(4,), dtype=int32)


In [ ]:
x1=tf.constant([3,5,63,1,2,3,1])
x2=tf.constant([2])
print(tf.add(x1,x2))

tf.Tensor([ 5  7 65  3  4  5  3], shape=(7,), dtype=int32)


In [ ]:
from tensorflow import linalg
x1=tf.constant([[1,2,3],[4,5,6],[7,8,9]],dtype=tf.float32)
x2=tf.constant([[2,3,5,],[3,1,9],[9,2,6]],dtype=tf.float32)
print(tf.expand_dims(x1, axis=0))
print(tf.einsum(('ij,ij -> ij'),x1,x2))
print(x2@tf.linalg.inv(x2))

tf.Tensor(
[[[1. 2. 3.]
  [4. 5. 6.]
  [7. 8. 9.]]], shape=(1, 3, 3), dtype=float32)
tf.Tensor(
[[ 2.  6. 15.]
 [12.  5. 54.]
 [63. 16. 54.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[ 9.9999994e-01  2.9802322e-08 -1.8626451e-08]
 [-1.8626451e-09  1.0000000e+00 -1.8626451e-08]
 [ 1.8626451e-08  0.0000000e+00  9.9999994e-01]], shape=(3, 3), dtype=float32)


DAY3: TENSORFLOW FUNCION

In [ ]:
x1=tf.constant([[12,2,3,9],[3,1,2,3],[5,6,7,4]])
x2=tf.constant([[11,8,12,2],[2,34,4,5],[2,7,8,9]])
print(x1.shape)
x1_exp=tf.expand_dims(x1,axis=1)
print(x1_exp.shape)
x1_exp=tf.squeeze(x1_exp)
print(x1_exp.shape)
x3=tf.concat([x1,x2],axis=0)
print(x3)
x3=tf.pad(x3,[[1,2],[3,4]])
print(x3)
tf.gather(x3,[3,2],axis=0)

(3, 4)
(3, 1, 4)
(3, 4)
tf.Tensor(
[[12  2  3  9]
 [ 3  1  2  3]
 [ 5  6  7  4]
 [11  8 12  2]
 [ 2 34  4  5]
 [ 2  7  8  9]], shape=(6, 4), dtype=int32)
tf.Tensor(
[[ 0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0 12  2  3  9  0  0  0  0]
 [ 0  0  0  3  1  2  3  0  0  0  0]
 [ 0  0  0  5  6  7  4  0  0  0  0]
 [ 0  0  0 11  8 12  2  0  0  0  0]
 [ 0  0  0  2 34  4  5  0  0  0  0]
 [ 0  0  0  2  7  8  9  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0]], shape=(9, 11), dtype=int32)


<tf.Tensor: shape=(2, 11), dtype=int32, numpy=
array([[0, 0, 0, 5, 6, 7, 4, 0, 0, 0, 0],
       [0, 0, 0, 3, 1, 2, 3, 0, 0, 0, 0]], dtype=int32)>